name: Deploy front-end aplication on EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v1
      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS_FRONT }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          source: ./
          target: ${{ secrets.DIR_TARGET }}
